[package]
name = "exo-managed-agents"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
futures.workspace = true
exo-mcp = { path = "../mcp" }
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
exoharness = { path = "../exoharness", features = ["http-client"] }
lingua.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["io"] }
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
exoharness = { path = "../exoharness", features = ["basic-backend"] }
tokio.workspace = true
